application: booloo-mozid
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /payload
  static_dir: payload
  mime_type: application/json

- url: /.*
  script: main.application
